# Generated by Django 6.0.3 on 2026-04-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_nutricionista_remove_paciente_user_paciente_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoalimentar',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
