# Generated by Django 6.0.3 on 2026-04-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_planoalimentar_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refeicao',
            name='dia_semana',
        ),
        migrations.AddField(
            model_name='planoalimentar',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
