# Generated by Django 6.0.3 on 2026-04-24 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_remove_refeicao_dia_semana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorias_diarias', models.FloatField()),
                ('proteina', models.FloatField()),
                ('carboidratos', models.FloatField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_nutricional', to='pacientes.paciente')),
            ],
        ),
    ]
