# Generated by Django 6.0.3 on 2026-04-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_metanutricional'),
    ]

    operations = [
        migrations.AddField(
            model_name='refeicao',
            name='dia_semana',
            field=models.CharField(choices=[('seg', 'Segunda'), ('ter', 'Terça'), ('qua', 'Quarta'), ('qui', 'Quinta'), ('sex', 'Sexta'), ('sab', 'Sábado'), ('dom', 'Domingo')], default='seg', max_length=3),
        ),
    ]
