# Generated by Django 6.0.3 on 2026-04-25 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_readd_refeicao_dia_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nutricionista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='pacientes.nutricionista'),
        ),
    ]
