# Generated by Django 6.0.3 on 2026-04-26 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_paciente_nutricionista_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='pacientes.paciente')),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='pacientes.refeicao')),
            ],
        ),
    ]
